- hosts: 172.31.37.53
  become: true
  become_user: root
  tasks:
  - name: Add private ip and private hostname of Puppet master
    blockinfile:
      path: /etc/hosts
      block: |
          172.31.43.129 ip-172-31-43-129.us-east-2.compute.internal
  - name: Download puppet package
    yum:
      name: https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
      state: present
  - name: Install puppet agent
    yum:
      name: puppet
      state: present
  - name: Add Puppet master's hostname
    blockinfile:
      path: /etc/puppetlabs/puppet/puppet.conf
      block: |
          server=ip-172-31-43-129.us-east-2.compute.internal
  - name: Enable Puppet
    systemd:
      name: puppet
      enabled: yes
  - name: Install docker on the test server 
    yum: 
      name: docker 
      state: present
  - name: Start docker service
    service: 
       name: docker 
       state: started
