- hosts: 172.31.37.53
  become: true
  become_user: root
  tasks:
  - name: Download puppet package
    yum:
      name: https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
      state: absent
  - name: Install puppet agent
    yum:
      name: puppet
      state: absent
  - name: Enable Puppet
    systemd:
      name: puppet
      enabled: no
